SELECT TABLE_SCHEMA + '.' + TABLE_NAME AS Tabela
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
ORDER BY TABLE_NAME;

SELECT TABLE_SCHEMA + '.' + TABLE_NAME AS Tabela
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%Order%'
   OR TABLE_NAME LIKE '%Sales%'
   OR TABLE_NAME LIKE '%Employee%'
   OR TABLE_NAME LIKE '%Store%'
   OR TABLE_NAME LIKE '%Product%'
   OR TABLE_NAME LIKE '%Item%'
ORDER BY TABLE_NAME;

SELECT TABLE_SCHEMA + '.' + TABLE_NAME AS Tabela, COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME IN ('OrderID', 'EmployeeID', 'StoreID', 'OrderDate', 'OrderItemID', 'ProductID', 'Quantity')
ORDER BY TABLE_NAME, ORDINAL_POSITION;
